package com.joezeo.joefgame.dao.mapper;

import com.joezeo.joefgame.dao.pojo.IP;
import com.joezeo.joefgame.dao.pojo.IPExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IPMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    long countByExample(IPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int deleteByExample(IPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int insert(IP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int insertSelective(IP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    List<IP> selectByExampleWithRowbounds(IPExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    List<IP> selectByExample(IPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    IP selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") IP record, @Param("example") IPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int updateByExample(@Param("record") IP record, @Param("example") IPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int updateByPrimaryKeySelective(IP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    int updateByPrimaryKey(IP record);
}