package com.joezeo.joefgame.dao.mapper;

import com.joezeo.joefgame.dao.pojo.TopicLikeUser;
import com.joezeo.joefgame.dao.pojo.TopicLikeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TopicLikeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    long countByExample(TopicLikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int deleteByExample(TopicLikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int insert(TopicLikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int insertSelective(TopicLikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    List<TopicLikeUser> selectByExampleWithRowbounds(TopicLikeUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    List<TopicLikeUser> selectByExample(TopicLikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    TopicLikeUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") TopicLikeUser record, @Param("example") TopicLikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int updateByExample(@Param("record") TopicLikeUser record, @Param("example") TopicLikeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int updateByPrimaryKeySelective(TopicLikeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_like_user
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    int updateByPrimaryKey(TopicLikeUser record);
}