package com.joezeo.joefgame.dao.mapper;

import com.joezeo.joefgame.dao.pojo.UserFollow;
import com.joezeo.joefgame.dao.pojo.UserFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    long countByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int deleteByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    List<UserFollow> selectByExampleWithRowbounds(UserFollowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    List<UserFollow> selectByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    UserFollow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int updateByExample(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_follow
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    int updateByPrimaryKey(UserFollow record);
}