package com.joezeo.joefgame.dao.pojo;

public class IP {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.id
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.gmt_create
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.gmt_modify
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.id
     *
     * @return the value of t_ip.id
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.id
     *
     * @param id the value for t_ip.id
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip
     *
     * @return the value of t_ip.ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip
     *
     * @param ip the value for t_ip.ip
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.gmt_create
     *
     * @return the value of t_ip.gmt_create
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.gmt_create
     *
     * @param gmtCreate the value for t_ip.gmt_create
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.gmt_modify
     *
     * @return the value of t_ip.gmt_modify
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.gmt_modify
     *
     * @param gmtModify the value for t_ip.gmt_modify
     *
     * @mbg.generated Wed Apr 08 13:31:03 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}