package com.joezeo.joefgame.dao.pojo;

public class SpiderFailedUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spider_failed_url.id
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spider_failed_url.url
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spider_failed_url.type
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spider_failed_url.gmt_create
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spider_failed_url.gmt_modify
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spider_failed_url.id
     *
     * @return the value of t_spider_failed_url.id
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spider_failed_url.id
     *
     * @param id the value for t_spider_failed_url.id
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spider_failed_url.url
     *
     * @return the value of t_spider_failed_url.url
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spider_failed_url.url
     *
     * @param url the value for t_spider_failed_url.url
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spider_failed_url.type
     *
     * @return the value of t_spider_failed_url.type
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spider_failed_url.type
     *
     * @param type the value for t_spider_failed_url.type
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spider_failed_url.gmt_create
     *
     * @return the value of t_spider_failed_url.gmt_create
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spider_failed_url.gmt_create
     *
     * @param gmtCreate the value for t_spider_failed_url.gmt_create
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spider_failed_url.gmt_modify
     *
     * @return the value of t_spider_failed_url.gmt_modify
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spider_failed_url.gmt_modify
     *
     * @param gmtModify the value for t_spider_failed_url.gmt_modify
     *
     * @mbg.generated Wed Mar 04 16:43:25 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}