package com.joezeo.joefgame.dao.pojo;

public class UserFavoriteApp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.id
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.userid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.appid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.type
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.gmt_create
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_favorite_app.gmt_modify
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.id
     *
     * @return the value of t_user_favorite_app.id
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.id
     *
     * @param id the value for t_user_favorite_app.id
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.userid
     *
     * @return the value of t_user_favorite_app.userid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.userid
     *
     * @param userid the value for t_user_favorite_app.userid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.appid
     *
     * @return the value of t_user_favorite_app.appid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.appid
     *
     * @param appid the value for t_user_favorite_app.appid
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.type
     *
     * @return the value of t_user_favorite_app.type
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.type
     *
     * @param type the value for t_user_favorite_app.type
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.gmt_create
     *
     * @return the value of t_user_favorite_app.gmt_create
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.gmt_create
     *
     * @param gmtCreate the value for t_user_favorite_app.gmt_create
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_favorite_app.gmt_modify
     *
     * @return the value of t_user_favorite_app.gmt_modify
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_favorite_app.gmt_modify
     *
     * @param gmtModify the value for t_user_favorite_app.gmt_modify
     *
     * @mbg.generated Fri Mar 20 15:27:20 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}