package com.joezeo.community.pojo;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.id
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifier
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.receiver
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.relatedid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long relatedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.relatedtype
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Integer relatedtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.status
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.gmt_create
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.gmt_modify
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.relatedName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private String relatedname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifierName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private String notifiername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.topicid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    private Long topicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.id
     *
     * @return the value of t_notification.id
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.id
     *
     * @param id the value for t_notification.id
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifier
     *
     * @return the value of t_notification.notifier
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifier
     *
     * @param notifier the value for t_notification.notifier
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.receiver
     *
     * @return the value of t_notification.receiver
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.receiver
     *
     * @param receiver the value for t_notification.receiver
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.relatedid
     *
     * @return the value of t_notification.relatedid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getRelatedid() {
        return relatedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.relatedid
     *
     * @param relatedid the value for t_notification.relatedid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setRelatedid(Long relatedid) {
        this.relatedid = relatedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.relatedtype
     *
     * @return the value of t_notification.relatedtype
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Integer getRelatedtype() {
        return relatedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.relatedtype
     *
     * @param relatedtype the value for t_notification.relatedtype
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setRelatedtype(Integer relatedtype) {
        this.relatedtype = relatedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.status
     *
     * @return the value of t_notification.status
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.status
     *
     * @param status the value for t_notification.status
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.gmt_create
     *
     * @return the value of t_notification.gmt_create
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.gmt_create
     *
     * @param gmtCreate the value for t_notification.gmt_create
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.gmt_modify
     *
     * @return the value of t_notification.gmt_modify
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.gmt_modify
     *
     * @param gmtModify the value for t_notification.gmt_modify
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.relatedName
     *
     * @return the value of t_notification.relatedName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public String getRelatedname() {
        return relatedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.relatedName
     *
     * @param relatedname the value for t_notification.relatedName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setRelatedname(String relatedname) {
        this.relatedname = relatedname == null ? null : relatedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifierName
     *
     * @return the value of t_notification.notifierName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public String getNotifiername() {
        return notifiername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifierName
     *
     * @param notifiername the value for t_notification.notifierName
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setNotifiername(String notifiername) {
        this.notifiername = notifiername == null ? null : notifiername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.topicid
     *
     * @return the value of t_notification.topicid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public Long getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.topicid
     *
     * @param topicid the value for t_notification.topicid
     *
     * @mbg.generated Mon Feb 17 18:00:19 CST 2020
     */
    public void setTopicid(Long topicid) {
        this.topicid = topicid;
    }
}