package com.joezeo.community.pojo;

public class ProxyIP {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.id
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.address
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.port
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.type
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.speed
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Double speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.connectTime
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Double connecttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.survive
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private String survive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.gmt_create
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_proxy_ip.gmt_modify
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.id
     *
     * @return the value of t_proxy_ip.id
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.id
     *
     * @param id the value for t_proxy_ip.id
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.address
     *
     * @return the value of t_proxy_ip.address
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.address
     *
     * @param address the value for t_proxy_ip.address
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.port
     *
     * @return the value of t_proxy_ip.port
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.port
     *
     * @param port the value for t_proxy_ip.port
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.type
     *
     * @return the value of t_proxy_ip.type
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.type
     *
     * @param type the value for t_proxy_ip.type
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.speed
     *
     * @return the value of t_proxy_ip.speed
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.speed
     *
     * @param speed the value for t_proxy_ip.speed
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.connectTime
     *
     * @return the value of t_proxy_ip.connectTime
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Double getConnecttime() {
        return connecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.connectTime
     *
     * @param connecttime the value for t_proxy_ip.connectTime
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setConnecttime(Double connecttime) {
        this.connecttime = connecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.survive
     *
     * @return the value of t_proxy_ip.survive
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public String getSurvive() {
        return survive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.survive
     *
     * @param survive the value for t_proxy_ip.survive
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setSurvive(String survive) {
        this.survive = survive == null ? null : survive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.gmt_create
     *
     * @return the value of t_proxy_ip.gmt_create
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.gmt_create
     *
     * @param gmtCreate the value for t_proxy_ip.gmt_create
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_proxy_ip.gmt_modify
     *
     * @return the value of t_proxy_ip.gmt_modify
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_proxy_ip.gmt_modify
     *
     * @param gmtModify the value for t_proxy_ip.gmt_modify
     *
     * @mbg.generated Sun Feb 09 13:23:05 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}