insert into t_tag values (default,"javascript",1);
insert into t_tag values (default,"php""css",1);
insert into t_tag values (default,"html",1);
insert into t_tag values (default,"html5",1);
insert into t_tag values (default,"java",1);
insert into t_tag values (default,"node.js",1);
insert into t_tag values (default,"python",1);
insert into t_tag values (default,"c++",1);
insert into t_tag values (default,"c",1);
insert into t_tag values (default,"golang",1);
insert into t_tag values (default,"objective-c",1);
insert into t_tag values (default,"typescript",1);
insert into t_tag values (default,"shell",1);
insert into t_tag values (default,"swift",1);
insert into t_tag values (default,"c#",1);
insert into t_tag values (default,"sass",1);
insert into t_tag values (default,"ruby",1);
insert into t_tag values (default,"bash",1);
insert into t_tag values (default,"less",1);
insert into t_tag values (default,"asp.net",1);
insert into t_tag values (default,"lua",1);
insert into t_tag values (default,"scala",1);
insert into t_tag values (default,"coffeescript",1);
insert into t_tag values (default,"actionscript",1);
insert into t_tag values (default,"rust",1);
insert into t_tag values (default,"erlang",1);
insert into t_tag values (default,"perl",1);

insert into t_tag values (default,"laravel",2);
insert into t_tag values (default,"spring",2);
insert into t_tag values (default,"express",2);
insert into t_tag values (default,"django",2);
insert into t_tag values (default,"flask",2);
insert into t_tag values (default,"yii",2);
insert into t_tag values (default,"ruby-on-rails",2);
insert into t_tag values (default,"tornado",2);
insert into t_tag values (default,"koa",2);
insert into t_tag values (default,"struts",2);

insert into t_tag values (default,"linux",3);
insert into t_tag values (default,"nginx",3);
insert into t_tag values (default,"docker",3);
insert into t_tag values (default,"apache",3);
insert into t_tag values (default,"ubuntu",3);
insert into t_tag values (default,"centos",3);
insert into t_tag values (default,"缓存 tomcat",3);
insert into t_tag values (default,"负载均衡",3);
insert into t_tag values (default,"unix",3);
insert into t_tag values (default,"hadoop",3);
insert into t_tag values (default,"windows-server",3);

insert into t_tag values (default,"mysql",4);
insert into t_tag values (default,"redis",4);
insert into t_tag values (default,"mongodb",4);
insert into t_tag values (default,"sql",4);
insert into t_tag values (default,"oracle",4);
insert into t_tag values (default,"nosql memcached",4);
insert into t_tag values (default,"sqlserver",4);
insert into t_tag values (default,"postgresql",4);
insert into t_tag values (default,"sqlite",4);

insert into t_tag values (default,"git",5);
insert into t_tag values (default,"github",5);
insert into t_tag values (default,"visual-studio-code",5);
insert into t_tag values (default,"vim",5);
insert into t_tag values (default,"sublime-text",5);
insert into t_tag values (default,"xcode intellij-idea",5);
insert into t_tag values (default,"eclipse",5);
insert into t_tag values (default,"maven",5);
insert into t_tag values (default,"ide",5);
insert into t_tag values (default,"svn",5);
insert into t_tag values (default,"visual-studio",5);
insert into t_tag values (default,"atom emacs",5);
insert into t_tag values (default,"textmate",5);
insert into t_tag values (default,"hg",5);